name: Publish website

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy through SFTP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: sftp://asmi.ro/ghid
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          git-ftp-args: --insecure
